### ISSUE TITLE
src/crawl.py : os.system() 에러 문제

### ISSUE THREAD

**Issue by JaehyoJJAng** [JaehyoJJAng/Coupang-Review-Crawling#3]
[src/crawl.py](https://github.com/JaehyoJJAng/Coupang-Review-Crawling/blob/main/src/crawl.py) 파일에서 
input_review_url 메소드와 input_page_cnt 메소드에 존재하는 os.system() 함수는 
**OS 버전**에 따라서 사용방법이 조금 달라질 수 있습니다

- Mac
```python
os.system('clear')
```

- Windows
```python
os.system('cls')
```

**Comment by kevinssic** [comment]
안녕하세요, 파이썬을 공부하고 있는데요,
올려주신 코드를  사용해 보면, crawl.py 내 코드 중
fileName = results[0][0]['prod_name'] + '.xlsx' 코드에서 IndexError: list index out of range 에러가 발생합니다.
여러 방법으로 수정해 보는데 동일한 에러가 나오는데요, 한번 확인해 주실 수 있으실까요?
미리 감사드립니다.

**Comment by JaehyoJJAng** [comment]
> 안녕하세요, 파이썬을 공부하고 있는데요, 올려주신 코드를 사용해 보면, crawl.py 내 코드 중 fileName = results[0][0]['prod_name'] + '.xlsx' 코드에서 IndexError: list index out of range 에러가 발생합니다. 여러 방법으로 수정해 보는데 동일한 에러가 나오는데요, 한번 확인해 주실 수 있으실까요? 미리 감사드립니다.

안녕하세요 케빈님. 아마도 headers.json 에 입력된 헤더 값이 잘못 업데이트 되었던 것 같습니다!
현재 관련 문제는 해결하였으니 다시 파일 받아가시면 이상 없이 실행 되실 것 같아요!

**Comment by kevinssic** [comment]
감사합니다. JaehyoJJAng님.
에러 코드만 보니 다른 부분 생각을 못했네요.
전달주신 코드로 잘 공부해 보겠습니다.
다시 한번 감사드립니다.
