### ISSUE TITLE
페이지 입력 없이 전부 다 긁어오도록 해주세요

### ISSUE THREAD

**Issue by mulkingJ** [JaehyoJJAng/Coupang-Review-Crawling#4]
페이지 입력 없이 리뷰 데이터를 전부 다 긁어올 수 있도록 수정해주실 수 있을까요?

**Comment by JaehyoJJAng** [comment]
전체 리뷰 수 / 1페이지당 보이는 리뷰 수 연산하면 페이지 입력 없이 처리가 가능할 것 같기는 합니다. 시간 생기면 수정해 보겠습니다

**Comment by mulkingJ** [comment]
네 감사합니다. 빨리 부탁드릴게요 급해서요

> 전체 리뷰 수 / 1페이지당 보이는 리뷰 수 연산하면 페이지 입력 없이 처리가 가능할 것 같기는 합니다. 시간 생기면 수정해 보겠습니다

**Comment by JaehyoJJAng** [comment]
해당 기능 업데이트 되었습니다.
