### ISSUE TITLE
헤더 파일 패스 오류 나오는데 어떻게 해야할까요?

### ISSUE THREAD

**Issue by wogusrh1** [JaehyoJJAng/Coupang-Review-Crawling#5]
안녕하세요.
헤더 파일 패스 오류 나오는데 어떻게 해야할까요?

 File "d:\Gdrive\workspace\Coupang-Review-Crawling\main.py", line 32, in <module>
    openpyxl_instance = OpenPyXL(headers_file_path)  # 인수를 받는 OpenPyXL 인스턴스 생성
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpenPyXL() takes no arguments

감사합니다.

**Comment by JaehyoJJAng** [comment]
수정하신 코드가 어떻게 되어있는지는 잘 모르겠지만, OpenPyXL 클래스는 인자를 받지 않아요. 

```python
openpyxl_instance = OpenPyXL()
openpyxl_instance.save_file()
```
헤더 파일의 경우 `Coupang` 클래스에서 처리하므로, OpenPyXL 클래스에서는 따로 인자를 넣을 필요가 없어용.
