### ISSUE TITLE
비동기 기능 업데이트 요청

### ISSUE THREAD

**Issue by mulkingJ** [JaehyoJJAng/Coupang-Review-Crawling#6]
안녕하세요! 해당 프로젝트 clone 하여 잘 사용 중입니다!

그런데 다소 속도가 느려 비동기를 적용하려고 GPT랑 열심히 씨름 했었는데 잘 안되더라구요 ..

비동기로 동작 가능하도록 업데이트 가능할까요?

**Comment by JaehyoJJAng** [comment]
네. 시간 날 때 해드릴게요.
